name: Rip City Math
tagline: private tutoring in southeast portland
markdown: redcarpet
pygments: true
permalink: /post/:year/:month/:day/:title
address: 4737 SE Kelly St
city: Portland, Oregon, 97206
timezone: America/Los_Angeles
phone: 971-266-1213
email: ripcitymath@gmail.com
url: www.ripcitymath.com
author: Tia
gems:
  - jekyll-sitemap