name: Rip City Math
tagline: private tutoring in southeast portland
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title
address: 4737 SE Kelly St
city: Portland, Oregon, 97206
timezone: America/Los_Angeles
phone: 503-985-6884
email: tia@ripcitymath.com
url: www.ripcitymath.com
author: Tia
gems:
  - jekyll-sitemap